import type { MealBriefSeed } from "./types";

export const INTRO = "Mỗi hồ sơ là một khách thật với một mục tiêu thật.\n\nDựng khay ăn MỘT NGÀY cho họ bằng cách tìm món và điền số gam. Bảng số phía trên\ncho biết khay của bạn đang có bao nhiêu calo và đạm; chỉ tiêu và sai số cho phép\nghi ngay bên dưới mỗi con số.\n\nHệ thống KHÔNG báo bạn đã đạt hay chưa — tự bạn phải tính. Món khách không được\năn mà lọt vào khay thì hồ sơ đó mất trắng, dù các con số có đẹp tới đâu.";

export const BRIEFS: MealBriefSeed[] = [
  {
    kind: "CUT",
    clientProfile: "Chị Hương, 32 tuổi · 68kg · cao 158cm · nhân viên văn phòng, ngồi 9 tiếng/ngày.\nĐăng ký gói L1, mục tiêu giảm 5kg trong 2 tháng. Tập 6 buổi/tuần.\nĂn trưa ở căng tin công ty, tối tự nấu. Không dị ứng gì.",
    targetCalories: 1500,
    targetProtein: 110,
    tolerancePercent: 10,
    bannedFoods: [],
    explanation: "Thâm hụt vừa phải và đạm cao là xương sống của giai đoạn giảm cân:\ncắt calo mà bỏ đạm thì khách sụt cân bằng cơ chứ không phải bằng mỡ, và cân sẽ\ndội lại ngay khi ngừng. Đạm 110g ≈ 1.6g cho mỗi kg cân nặng — mức tối thiểu để\ngiữ cơ trong lúc thâm hụt. Muốn vừa đủ calo mà vẫn đủ đạm thì phải chọn nguồn\nđạm nạc (ức gà, cá, đậu phụ) chứ không thể lấy thịt mỡ cho nhanh.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Cô Lan, 45 tuổi · 72kg · cao 155cm · nội trợ, huyết áp cao đang uống thuốc.\nDỊ ỨNG HẢI SẢN — từng phải đi cấp cứu vì ăn nhầm tôm.\nĐăng ký gói L2, mục tiêu giảm 7kg trong 3 tháng. Tập 5 buổi/tuần.",
    targetCalories: 1600,
    targetProtein: 100,
    tolerancePercent: 10,
    bannedFoods: ["Tôm biển","Tôm đồng","Tôm khô","Cua bể","Cua đồng","Mực tươi","Mực khô"],
    explanation: "Hồ sơ này không khó về con số — nó khó ở chỗ bạn có đọc kỹ hay không.\nKhách dị ứng hải sản tới mức từng phải cấp cứu. Một khay ăn đúng chằn chặn calo\nvà đạm mà có tôm trong đó là một khay ăn có thể đưa khách vào bệnh viện, nên nó\nđược 0 điểm chứ không phải \"gần đúng\". Dị ứng không phải chuyện thương lượng.",
  },
  {
    kind: "BULK",
    clientProfile: "Em Trang, 25 tuổi · 48kg · cao 162cm · sinh viên năm cuối, hay bỏ bữa sáng.\nKHÔNG muốn giảm cân — muốn TĂNG 3kg và có đường nét cơ. Tập 4 buổi/tuần.\nThan \"tập mãi không lên được cân nào\".",
    targetCalories: 2200,
    targetProtein: 95,
    tolerancePercent: 10,
    bannedFoods: [],
    explanation: "Đây là hồ sơ bẫy. Phần lớn khách tới phòng tập là để giảm, nên phản xạ\ncủa HLV là cắt calo cho mọi người — và đó chính là tội phàm ăn phiên bản ngược:\năn theo thói quen của chính mình chứ không theo nhu cầu của khách. Em này gầy,\nhay bỏ bữa, muốn tăng cân: khay ăn phải THẶNG DƯ calo mới có chỗ cho cơ mọc.\nĐạm 95g ≈ 2g/kg là đủ; nhồi thêm đạm mà thiếu calo thì vẫn không lên được cân.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Mai, 28 tuổi · 62kg · cao 160cm · giáo viên mầm non, đứng và đi lại cả ngày.\nGói L1, mục tiêu giảm 4kg trong 2 tháng. Tập 5 buổi/tuần.\nĂn trưa ở trường, tối ăn cùng gia đình. Không dị ứng gì.",
    targetCalories: 1550, targetProtein: 105, tolerancePercent: 10, bannedFoods: [],
    explanation: "Nghề đứng cả ngày làm mức tiêu hao nền cao hơn dân văn phòng, nên thâm hụt vẫn đủ sâu mà không phải cắt xuống 1300. Đạm 105g ≈ 1.7g/kg giữ cơ trong lúc giảm.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Vân, 35 tuổi · 75kg · cao 162cm · kế toán, ngồi 9-10 tiếng, hay ăn vặt buổi chiều.\nGói L2, mục tiêu giảm 8kg trong 3 tháng. Tập 6 buổi/tuần.\nKhông bệnh nền, không dị ứng.",
    targetCalories: 1500, targetProtein: 120, tolerancePercent: 10, bannedFoods: [],
    explanation: "Thâm hụt khoảng 25% so với mức tiêu hao là vùng an toàn cho mục tiêu 8kg/3 tháng. Đạm 120g ≈ 1.6g/kg — với người ăn vặt nhiều thì đạm cao còn có tác dụng làm no, không chỉ để giữ cơ.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Thu, 41 tuổi · 80kg · cao 158cm · bán hàng online tại nhà, gần như không đi lại.\nGói L2, mục tiêu giảm 9kg. Tập 6 buổi/tuần.\nKhông dị ứng, ăn được mọi thứ.",
    targetCalories: 1500, targetProtein: 125, tolerancePercent: 10, bannedFoods: [],
    explanation: "Cân nặng lớn nhưng vận động ngoài buổi tập gần như bằng không, nên mức tiêu hao không cao như con số cân nặng gợi ý. Đạm 125g ≈ 1.6g/kg, và ở người ít vận động thì đạm cao càng quan trọng vì cơ mất nhanh hơn.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Ngọc, 26 tuổi · 58kg · cao 165cm · nhân viên marketing, chạy ngoài đường nhiều.\nMuốn giảm 3kg trước đám cưới, còn 6 tuần. Tập 5 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1650, targetProtein: 100, tolerancePercent: 10, bannedFoods: [],
    explanation: "Chỉ cần giảm 3kg và người này vốn không thừa nhiều, nên thâm hụt phải NHẸ thôi. Cắt sâu ở đây là khách hốc hác đúng ngày cưới — mục tiêu thật của khách không phải con số cân mà là trông thế nào trong ảnh.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Hà, 38 tuổi · 70kg · cao 155cm · có hai con nhỏ, ngủ khoảng 5 tiếng mỗi đêm.\nGói L2, mục tiêu giảm 6kg. Tập 5 buổi/tuần, hay phải nghỉ đột xuất.\nKhông dị ứng.",
    targetCalories: 1500, targetProtein: 115, tolerancePercent: 10, bannedFoods: [],
    explanation: "Thiếu ngủ kéo dài làm tăng cảm giác đói và giảm khả năng chịu đựng thâm hụt sâu. Đặt thâm hụt vừa phải, đạm cao (1.6g/kg) để no lâu — một khay ăn khắc nghiệt ở hồ sơ này gần như chắc chắn bị bỏ giữa chừng.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Loan, 30 tuổi · 66kg · cao 157cm · nhân viên ngân hàng, thường ăn tối lúc 9h.\nGói L1, mục tiêu giảm 5kg. Tập 6 buổi/tuần.\nKhông bệnh nền, không dị ứng.",
    targetCalories: 1450, targetProtein: 110, tolerancePercent: 10, bannedFoods: [],
    explanation: "Giờ ăn muộn không tự làm tăng cân — tổng calo mới quyết định. Đặt mức 1450 với đạm 1.7g/kg, và dồn phần lớn calo vào bữa tối cũng được, miễn cả ngày không vượt chỉ tiêu.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Trâm, 45 tuổi · 68kg · cao 160cm · giai đoạn tiền mãn kinh, hay bốc hoả và mất ngủ.\nGói L2, mục tiêu giảm 6kg. Tập 5 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1450, targetProtein: 115, tolerancePercent: 10, bannedFoods: [],
    explanation: "Từ tuổi này khối cơ mất nhanh hơn hẳn, nên đạm phải đẩy lên khoảng 1.7g/kg chứ không giữ mức thông thường. Thâm hụt vừa phải vì giấc ngủ đã kém sẵn.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Yến, 33 tuổi · 85kg · cao 163cm · béo phì độ 1, chưa từng tập bao giờ.\nGói L2, mục tiêu giảm 9kg trong 3 tháng. Tập 6 buổi/tuần nhưng cường độ còn thấp.\nKhông bệnh nền.",
    targetCalories: 1600, targetProtein: 130, tolerancePercent: 10, bannedFoods: [],
    explanation: "Người mới hoàn toàn thì buổi tập chưa đốt được nhiều, và mức 1600 đã là thâm hụt lớn với người này. Đặt thấp hơn nữa là bỏ tập trong hai tuần — giảm cân bền quan trọng hơn giảm nhanh.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Bích, 29 tuổi · 60kg · cao 168cm · đã tập 2 năm, nâng khá nặng.\nMuốn giảm mỡ mà giữ nguyên cơ. Tập 5 buổi/tuần, cường độ cao.\nKhông dị ứng.",
    targetCalories: 1750, targetProtein: 115, tolerancePercent: 8, bannedFoods: [],
    explanation: "Người đã có cơ và tập nặng thì thâm hụt phải nông (khoảng 15%) và đạm phải cao (gần 2g/kg), nếu không thì cơ mất trước mỡ. Sai số cũng hẹp hơn vì mục tiêu ở đây tinh hơn giảm cân thông thường.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Nga, 52 tuổi · 73kg · cao 156cm · đã nghỉ hưu, sinh hoạt nhẹ nhàng.\nGói L3, mục tiêu giảm 5kg và khoẻ hơn. Tập 4 buổi/tuần.\nKhông bệnh nền đang điều trị.",
    targetCalories: 1400, targetProtein: 115, tolerancePercent: 10, bannedFoods: [],
    explanation: "Tuổi cao, ít vận động ngoài buổi tập, mức tiêu hao thấp — nhưng đạm vẫn phải giữ cao (1.6g/kg) vì đây là nhóm mất cơ nhanh nhất. Cắt đạm ở hồ sơ này là đổi cân nặng lấy sức khoẻ.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Linh, 24 tuổi · 64kg · cao 159cm · học cao học, ăn ngoài cả ba bữa.\nGói L1, mục tiêu giảm 4kg. Tập 6 buổi/tuần.\nKhông dị ứng, ngân sách ăn uống hạn chế.",
    targetCalories: 1500, targetProtein: 105, tolerancePercent: 10, bannedFoods: [],
    explanation: "Con số không khó, cái khó là khách ăn ngoài nên khay ăn phải dựng từ những món phổ biến và rẻ. Đạm 1.6g/kg lấy từ trứng, đậu phụ, ức gà là đủ mà không đội chi phí.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Phương, 36 tuổi · 78kg · cao 165cm · quản lý kinh doanh, đi công tác 2 tuần/tháng.\nGói L2, mục tiêu giảm 8kg. Tập 5 buổi/tuần khi ở nhà.\nKhông dị ứng.",
    targetCalories: 1550, targetProtein: 125, tolerancePercent: 10, bannedFoods: [],
    explanation: "Thâm hụt khoảng 25%. Với người đi công tác liên tục, khay ăn phải dựng từ món dễ tìm ở nhà hàng và khách sạn chứ không phải món phải tự nấu — đúng chỉ tiêu mà không thực hiện được thì cũng bằng không.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Dung, 31 tuổi · 69kg · cao 161cm · sinh con 8 tháng trước, đã cai sữa hoàn toàn.\nGói L1, muốn về lại cân nặng trước sinh (giảm 6kg). Tập 5 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1550, targetProtein: 115, tolerancePercent: 10, bannedFoods: [],
    explanation: "Đã cai sữa nên không còn phần calo cho việc tiết sữa — tính như người bình thường. Thâm hụt vừa phải và đạm 1.7g/kg, vì cơ thể sau sinh cần phục hồi chứ không chỉ cần nhẹ cân.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Hạnh, 47 tuổi · 71kg · cao 154cm · thoái hoá khớp gối nhẹ, chỉ đi bộ và tập máy.\nGói L3, mục tiêu giảm 5kg để đỡ gánh nặng lên gối. Tập 4 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1400, targetProtein: 120, tolerancePercent: 10, bannedFoods: [],
    explanation: "Vận động bị giới hạn nên phần lớn thâm hụt phải đến từ khay ăn. Đạm đẩy lên 1.7g/kg để giữ cơ đùi — chính khối cơ đó mới là thứ đỡ cho khớp gối, giảm cân mà mất cơ thì gối còn đau hơn.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Quyên, 27 tuổi · 55kg · cao 160cm · cân nặng bình thường nhưng tỉ lệ mỡ 32%.\nMuốn giảm mỡ, không quan tâm con số cân. Tập 5 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1650, targetProtein: 105, tolerancePercent: 8, bannedFoods: [],
    explanation: "Hồ sơ dễ đặt sai: nhìn 55kg thì tưởng không cần giảm, nhìn mỡ 32% thì tưởng phải cắt mạnh. Đáp án là thâm hụt rất nhẹ với đạm gần 2g/kg — mục tiêu là đổi thành phần cơ thể chứ không phải làm nhẹ cái cân.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Tú, 39 tuổi · 82kg · cao 167cm · huyết áp hơi cao, bác sĩ dặn giảm cân, chưa dùng thuốc.\nGói L2, mục tiêu giảm 9kg. Tập 5 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1600, targetProtein: 130, tolerancePercent: 10, bannedFoods: [],
    explanation: "Chưa dùng thuốc nên chưa phải hồ sơ có ràng buộc y tế, nhưng vẫn nên hạn chế món mặn và nhiều mỡ động vật. Thâm hụt khoảng 24%, đạm 1.6g/kg.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Nhung, 34 tuổi · 63kg · cao 152cm · nhân viên hành chính, dáng người nhỏ.\nGói L1, mục tiêu giảm 5kg. Tập 6 buổi/tuần. Đã thử nhiều lần trước đây nhưng đều bỏ.\nKhông dị ứng.",
    targetCalories: 1400, targetProtein: 105, tolerancePercent: 10, bannedFoods: [],
    explanation: "Người thấp thì mức tiêu hao nền thấp thật, nên chỉ tiêu calo phải xuống 1400 — nhưng không thấp hơn nữa, vì tiền sử bỏ giữa chừng nói rằng khách này đã từng bị ép quá tay. Đạm 1.7g/kg để đỡ đói.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị An, 43 tuổi · 76kg · cao 159cm · điều dưỡng, làm ca đêm 3 đêm/tuần.\nGói L2, mục tiêu giảm 7kg. Tập 5 buổi/tuần vào ngày nghỉ ca.\nKhông dị ứng.",
    targetCalories: 1500, targetProtein: 125, tolerancePercent: 10, bannedFoods: [],
    explanation: "Làm ca đêm đảo lộn giờ ăn nhưng không đổi tổng nhu cầu. Chỉ tiêu tính như bình thường; cái phải điều chỉnh là cách chia bữa, và đạm cao (1.6g/kg) để đỡ ăn vặt trong ca trực.",
  },
  {
    kind: "CUT",
    clientProfile: "Chị Thảo, 25 tuổi · 71kg · cao 170cm · từng là vận động viên bóng chuyền, khối cơ lớn.\nMuốn giảm 5kg mỡ, giữ nguyên sức. Tập 6 buổi/tuần, cường độ cao.\nKhông dị ứng.",
    targetCalories: 1900, targetProtein: 130, tolerancePercent: 8, bannedFoods: [],
    explanation: "Khối cơ lớn và tập nặng làm mức tiêu hao cao hơn hẳn người cùng cân nặng — đặt 1500 ở hồ sơ này là cắt quá tay và tụt sức ngay tuần đầu. Đây là chỗ dễ sai nhất: cùng một con số cân, hai người có thể cần lệch nhau 400 calo.",
  },
  {
    kind: "BULK",
    clientProfile: "Em Chi, 22 tuổi · 44kg · cao 158cm · sinh viên, ăn ngày hai bữa vì dậy muộn.\nMuốn TĂNG 4kg và có dáng săn chắc. Tập 4 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1900, targetProtein: 90, tolerancePercent: 10, bannedFoods: [],
    explanation: "Phải THẶNG DƯ calo mới có chỗ cho cơ mọc. Đạm 90g ≈ 2g/kg là đủ; nhồi thêm đạm mà thiếu calo thì vẫn không lên được cân nào. Cái khó là ăn cho đủ 1900 với người quen ăn hai bữa.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Diệp, 30 tuổi · 47kg · cao 160cm · vừa qua một đợt ốm dài, sụt 5kg.\nMuốn lấy lại cân và sức. Tập 4 buổi/tuần, còn nhanh mệt.\nKhông dị ứng.",
    targetCalories: 1850, targetProtein: 95, tolerancePercent: 10, bannedFoods: [],
    explanation: "Người mới ốm dậy cần thặng dư nhưng dạ dày chưa ăn được nhiều, nên khay ăn phải chọn món đậm năng lượng trong ít thể tích. Đạm 2g/kg để phục hồi khối cơ đã mất.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Hoa, 34 tuổi · 50kg · cao 155cm · muốn tăng cơ vùng mông và đùi, không muốn tăng mỡ bụng.\nTập 5 buổi/tuần, chủ yếu bài chân.\nKhông dị ứng.",
    targetCalories: 1900, targetProtein: 100, tolerancePercent: 10, bannedFoods: [],
    explanation: "Không có cách nào tăng cơ mà không thặng dư calo — \"tăng cơ chỗ này, giảm mỡ chỗ kia\" là điều khách hay xin và HLV hay gật bừa. Thặng dư vừa phải với đạm 2g/kg là câu trả lời trung thực nhất.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Trang, 27 tuổi · 52kg · cao 165cm · người mẫu ảnh, cần thêm cơ mà không đổi số đo eo.\nTập 5 buổi/tuần, cường độ cao.\nKhông dị ứng.",
    targetCalories: 2100, targetProtein: 105, tolerancePercent: 8, bannedFoods: [],
    explanation: "Thặng dư nhỏ (khoảng 10%) để phần tăng nghiêng về cơ chứ không về mỡ, kèm đạm 2g/kg. Sai số hẹp vì mục tiêu tinh — thặng dư quá tay ở hồ sơ này là hỏng đúng cái khách đi làm bằng.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Ly, 29 tuổi · 45kg · cao 162cm · ăn rất ít, hay bỏ bữa sáng và bữa tối.\nMuốn tăng 5kg. Tập 4 buổi/tuần.\nKhông dị ứng, nhưng không ăn được nhiều một lúc.",
    targetCalories: 1950, targetProtein: 90, tolerancePercent: 10, bannedFoods: [],
    explanation: "Chỉ tiêu là 1950 nhưng khách không ăn nổi ba bữa lớn, nên khay phải chia thành nhiều bữa nhỏ và ưu tiên món đậm calo. Đặt chỉ tiêu thấp xuống cho \"dễ đạt\" là bỏ luôn mục tiêu của khách.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Xuân, 38 tuổi · 49kg · cao 157cm · sau sinh sụt cân nhiều, con đã cai sữa.\nMuốn tăng 4kg và khoẻ lại. Tập 4 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1850, targetProtein: 95, tolerancePercent: 10, bannedFoods: [],
    explanation: "Đã cai sữa nên không cộng thêm phần calo cho việc tiết sữa. Thặng dư khoảng 18% và đạm 2g/kg để phục hồi khối cơ mất trong thai kỳ và giai đoạn nuôi con nhỏ.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Kim, 24 tuổi · 46kg · cao 153cm · đã tập 3 tháng đều đặn nhưng cân không nhúc nhích.\nMuốn tăng 3kg. Tập 5 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 2000, targetProtein: 90, tolerancePercent: 10, bannedFoods: [],
    explanation: "Tập đều mà cân không lên gần như luôn có một nguyên nhân: ăn chưa đủ. Đặt thặng dư rõ rệt, và cái khách cần nhất từ HLV ở đây là một con số cụ thể để ăn theo, không phải lời khuyên \"ăn nhiều lên\".",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Oanh, 32 tuổi · 53kg · cao 168cm · dáng cao gầy, ăn nhiều mà không lên cân.\nMuốn tăng 5kg trong 4 tháng. Tập 4 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 2100, targetProtein: 105, tolerancePercent: 10, bannedFoods: [],
    explanation: "Người cao thì mức tiêu hao nền cao, nên \"ăn nhiều\" theo cảm nhận của khách vẫn có thể chưa đủ. Con số 2100 cho thấy khoảng cách thật giữa cái khách nghĩ mình ăn và cái cơ thể cần.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Nhàn, 26 tuổi · 48kg · cao 156cm · nhân viên văn phòng, muốn tăng 3kg trong 3 tháng.\nTập 4 buổi/tuần. Sợ tăng mỡ bụng.\nKhông dị ứng.",
    targetCalories: 1950, targetProtein: 95, tolerancePercent: 10, bannedFoods: [],
    explanation: "Thặng dư vừa phải (khoảng 15%) là mức tăng cân chậm nhưng phần lớn vào cơ. Đây cũng là con số để trấn an nỗi sợ tăng mỡ của khách bằng dữ kiện chứ không bằng lời hứa.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Tâm, 41 tuổi · 51kg · cao 159cm · loãng xương nhẹ, bác sĩ khuyên tập tạ và ăn đủ đạm.\nMuốn tăng 3kg cơ. Tập 4 buổi/tuần.\nKhông dị ứng, không kiêng gì.",
    targetCalories: 1850, targetProtein: 105, tolerancePercent: 10, bannedFoods: [],
    explanation: "Đạm đẩy lên hơn 2g/kg vì mục tiêu là khối cơ và mật độ xương, không phải cân nặng. Thặng dư nhẹ để phần tăng đi vào cơ — đây là hồ sơ mà cắt calo sẽ đi ngược hẳn lời dặn của bác sĩ.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Vi, 23 tuổi · 43kg · cao 150cm · nhẹ cân từ nhỏ, người nhà lo lắng.\nMuốn tăng 4kg. Tập 4 buổi/tuần, mới bắt đầu.\nKhông dị ứng.",
    targetCalories: 1800, targetProtein: 85, tolerancePercent: 10, bannedFoods: [],
    explanation: "Vóc người nhỏ nên chỉ tiêu tuyệt đối không cao, nhưng so với mức tiêu hao của khách thì đây đã là thặng dư đáng kể. Đạm 2g/kg, và tăng dần chứ đừng nhảy thẳng lên mức này trong một ngày.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Hằng, 35 tuổi · 55kg · cao 163cm · đã giảm xong 10kg, giờ muốn xây cơ cho dáng đầy hơn.\nTập 5 buổi/tuần, nâng khá nặng.\nKhông dị ứng.",
    targetCalories: 2050, targetProtein: 110, tolerancePercent: 8, bannedFoods: [],
    explanation: "Khách vừa qua một giai đoạn giảm dài nên rất sợ con số calo cao — nhưng giữ thâm hụt tiếp là mắc kẹt mãi ở chỗ này. Thặng dư nhỏ và đạm 2g/kg, và phần khó nhất của HLV là thuyết phục khách rằng ăn thêm không phải là thất bại.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Ánh, 28 tuổi · 50kg · cao 161cm · tập 6 buổi/tuần cường độ cao, hay chóng mặt cuối buổi.\nMuốn tăng 3kg cơ. Không bệnh nền.\nKhông dị ứng.",
    targetCalories: 2200, targetProtein: 100, tolerancePercent: 10, bannedFoods: [],
    explanation: "Chóng mặt cuối buổi ở người tập nhiều mà nhẹ cân gần như luôn là dấu hiệu ăn không đủ so với khối lượng vận động. Chỉ tiêu cao hẳn ở đây là để bù phần đó, không phải để tăng cân nhanh.",
  },
  {
    kind: "BULK",
    clientProfile: "Chị Yên, 45 tuổi · 52kg · cao 158cm · thấy tay chân mềm nhão dần vài năm nay.\nKhông muốn tăng cân, nhưng muốn chắc người. Tập 4 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1750, targetProtein: 110, tolerancePercent: 10, bannedFoods: [],
    explanation: "Khách nói \"không muốn tăng cân\" nhưng cái họ mô tả là mất cơ theo tuổi, và xây lại cơ thì cần thặng dư nhẹ cùng đạm rất cao (hơn 2g/kg). Nghe theo câu chữ của khách mà đặt thâm hụt là làm đúng điều khách sợ.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Bảo, 33 tuổi · 66kg · cao 160cm · KHÔNG DUNG NẠP LACTOSE, uống sữa là đau bụng cả ngày.\nGói L1, mục tiêu giảm 5kg. Tập 5 buổi/tuần.\nKhông dị ứng gì khác.",
    targetCalories: 1500, targetProtein: 110, tolerancePercent: 10,
    bannedFoods: ["Sữa bò tươi", "Sữa dê tươi", "Sữa chua (từ sữa bò)", "Sữa bột toàn phần", "Sữa bột tách béo", "Sữa đặc có đường Việt Nam"],
    explanation: "Con số không khó; cái khó là lấy đủ 110g đạm khi mất hẳn nhóm sữa — nguồn tiện nhất của phần lớn thực đơn giảm cân. Phải bù bằng trứng, thịt nạc, cá và đậu phụ.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Cẩm, 29 tuổi · 58kg · cao 157cm · ĂN CHAY TRƯỜNG, không dùng thịt, cá, trứng, sữa.\nGói L1, mục tiêu giảm 4kg. Tập 5 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1500, targetProtein: 90, tolerancePercent: 10,
    bannedFoods: ["Thịt lợn nạc", "Thịt bò loại I", "Thịt gà ta", "Cá chép", "Tôm biển", "Trứng gà", "Trứng vịt", "Sữa bò tươi"],
    explanation: "Đạm đặt 90g chứ không phải 110g như hồ sơ tương đương ăn mặn — đó là mức thực tế đạt được từ nguồn thực vật mà không phải ăn một lượng đậu phi lý. Ép chỉ tiêu đạm cao rồi bảo khách \"cố ăn\" là kê một thực đơn không ai theo nổi.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Đào, 36 tuổi · 74kg · cao 158cm · TIỂU ĐƯỜNG TYPE 2, đang uống thuốc theo đơn.\nGói L2, mục tiêu giảm 7kg, có giấy đồng ý của bác sĩ. Tập 5 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1500, targetProtein: 115, tolerancePercent: 10,
    bannedFoods: ["Đường kính", "Đường cát", "Mật ong", "Sữa đặc có đường Việt Nam", "Kẹo sữa", "Kẹo sô cô la"],
    explanation: "Thâm hụt vừa phải và đạm cao, nhưng điều quyết định là loại bỏ đường tự do — người đang dùng thuốc hạ đường huyết mà ăn đường nhanh thì đường huyết dao động mạnh. Mọi thay đổi lớn hơn thế phải qua bác sĩ điều trị.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Ánh Tuyết, 31 tuổi · 63kg · cao 161cm · DỊ ỨNG ĐẬU PHỘNG, từng phải dùng thuốc chống sốc.\nGói L1, mục tiêu giảm 4kg. Tập 5 buổi/tuần.\nKhông kiêng gì khác.",
    targetCalories: 1500, targetProtein: 105, tolerancePercent: 10,
    bannedFoods: ["Lạc hạt", "Lạc chao dầu", "Kẹo lạc", "Dầu lạc", "Dầu thảo mộc (Lạc, vừng, cám...)"],
    explanation: "Hồ sơ này không khó về số mà khó ở chỗ đọc kỹ: lạc còn nấp trong dầu và trong đồ ngọt, không chỉ ở dạng hạt. Một khay ăn đúng chằn chặn calo mà có dầu lạc trong đó là khay ăn đưa khách đi cấp cứu.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Hường, 27 tuổi · 61kg · cao 156cm · DỊ ỨNG TRỨNG, nổi mề đay mỗi lần ăn nhầm.\nGói L1, mục tiêu giảm 4kg. Tập 6 buổi/tuần.\nKhông kiêng gì khác.",
    targetCalories: 1450, targetProtein: 105, tolerancePercent: 10,
    bannedFoods: ["Trứng gà", "Trứng vịt", "Trứng chim cút", "Trứng vịt lộn"],
    explanation: "Mất nguồn đạm rẻ và tiện nhất của thực đơn giảm cân, nên phải dựng lại bằng thịt nạc, cá và sữa. Đây là kiểu hồ sơ mà HLV quen tay rất dễ đưa trứng vào theo phản xạ.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Kiều, 39 tuổi · 69kg · cao 159cm · BỆNH GÚT, acid uric cao, đã có đợt sưng đau ngón chân.\nGói L2, mục tiêu giảm 6kg. Tập 5 buổi/tuần.\nBác sĩ dặn hạn chế hải sản và nội tạng.",
    targetCalories: 1500, targetProtein: 100, tolerancePercent: 10,
    bannedFoods: ["Tôm biển", "Tôm đồng", "Cua bể", "Mực tươi", "Trứng cá muối", "Gan lợn", "Gan bò", "Gan gà"],
    explanation: "Vẫn cần đạm để giữ cơ, nhưng phải lấy từ nguồn ít purin — thịt nạc trắng, trứng, sữa, đậu phụ — thay vì hải sản và nội tạng. Đặt đạm 100g thay vì 110g cũng là một cách nới cho an toàn.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Loan, 30 tuổi · 55kg · cao 160cm · ĐANG MANG THAI 5 THÁNG, thai kỳ bình thường.\nBác sĩ đồng ý cho tập nhẹ. Tập 3 buổi/tuần, chỉ bài không tác động mạnh.\nKhông dị ứng.",
    targetCalories: 2050, targetProtein: 95, tolerancePercent: 10, bannedFoods: [],
    explanation: "TUYỆT ĐỐI KHÔNG đặt thâm hụt. Thai kỳ giữa cần thêm khoảng 300 calo mỗi ngày so với bình thường; đặt chỉ tiêu 1500 ở đây là một khay ăn có hại cho hai người. Đây là hồ sơ đo phản xạ cắt calo của HLV rõ nhất trong cả vòng.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Mến, 44 tuổi · 70kg · cao 154cm · SUY THẬN ĐỘ 2, bác sĩ dặn hạn chế đạm.\nGói L3, mục tiêu giảm 4kg và vận động đều. Tập 4 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1450, targetProtein: 65, tolerancePercent: 10, bannedFoods: [],
    explanation: "Đây là hồ sơ duy nhất mà đạm phải đặt THẤP, khoảng 0.9g/kg, theo lời dặn của bác sĩ. Phản xạ nghề nghiệp là đẩy đạm lên 1.6g/kg, và đúng ở đây thì phản xạ ấy gây hại — chỉ định y tế đứng trên nguyên tắc chung.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Nguyệt, 35 tuổi · 67kg · cao 162cm · ĐANG CHO CON BÚ, bé 6 tháng, bú mẹ hoàn toàn.\nMuốn giảm cân nhưng không được ảnh hưởng nguồn sữa. Tập 4 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 2050, targetProtein: 110, tolerancePercent: 10, bannedFoods: [],
    explanation: "Tiết sữa tốn khoảng 400-500 calo mỗi ngày, nên chỉ tiêu vẫn cao dù mục tiêu là giảm cân. Cắt sâu ở đây là mất sữa — cân sẽ xuống chậm và đó là điều phải giải thích trước với khách chứ không phải điều để chiều theo.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Phượng, 28 tuổi · 59kg · cao 158cm · DỊ ỨNG ĐẬU NÀNH, ăn đậu phụ là mẩn ngứa.\nGói L1, mục tiêu giảm 4kg. Tập 5 buổi/tuần.\nKhông kiêng gì khác.",
    targetCalories: 1500, targetProtein: 105, tolerancePercent: 10,
    bannedFoods: ["Đậu tương (đậu nành)", "Đậu phụ", "Đậu phụ nướng", "Đậu phụ chúc", "Sữa đậu nành (100g đậu/lít)", "Sữa bột đậu nành", "Dầu đậu tương", "Xì dầu"],
    explanation: "Đậu nành nấp ở rất nhiều chỗ, kể cả xì dầu và dầu ăn — đọc lướt là lọt. Bù đạm bằng thịt nạc, cá, trứng và sữa.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Sương, 50 tuổi · 72kg · cao 153cm · MỠ MÁU CAO, đang uống thuốc, bác sĩ dặn giảm mỡ động vật.\nGói L3, mục tiêu giảm 6kg. Tập 4 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1400, targetProtein: 115, tolerancePercent: 10,
    bannedFoods: ["Mỡ lợn nước", "Mỡ lợn muối", "Thịt lợn mỡ", "Ba chỉ lợn", "Gan lợn", "Bơ"],
    explanation: "Vẫn giữ đạm cao (1.6g/kg) nhưng phải lấy từ nguồn nạc, và bỏ hẳn mỡ động vật cùng nội tạng. Đây là hồ sơ mà chọn sai nguồn đạm thì các con số vẫn đẹp nhưng khay ăn đi ngược đơn thuốc của khách.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Trúc, 26 tuổi · 64kg · cao 165cm · HỘI CHỨNG RUỘT KÍCH THÍCH, sữa và đồ nhiều dầu là đau bụng.\nGói L1, mục tiêu giảm 4kg. Tập 5 buổi/tuần.\nKhông dị ứng nặng.",
    targetCalories: 1550, targetProtein: 105, tolerancePercent: 10,
    bannedFoods: ["Sữa bò tươi", "Sữa chua (từ sữa bò)", "Sữa đặc có đường Việt Nam", "Mỡ lợn nước", "Bánh quẩy"],
    explanation: "Không phải dị ứng nhưng ảnh hưởng trực tiếp tới việc khách có theo nổi thực đơn hay không. Chọn món dễ tiêu, chia nhỏ bữa, và tránh nhóm khách đã tự biết là mình không hợp.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Uyên, 37 tuổi · 77kg · cao 160cm · THIẾU MÁU THIẾU SẮT, đang uống viên sắt.\nĐỒNG THỜI DỊ ỨNG HẢI SẢN. Gói L2, mục tiêu giảm 7kg. Tập 5 buổi/tuần.",
    targetCalories: 1550, targetProtein: 125, tolerancePercent: 10,
    bannedFoods: ["Tôm biển", "Tôm đồng", "Tôm khô", "Cua bể", "Cua đồng", "Mực tươi", "Mực khô"],
    explanation: "Hai ràng buộc chồng lên nhau: cần nguồn sắt tốt (thịt đỏ, gan, rau lá đậm) nhưng lại mất hẳn nhóm hải sản. Đây là hồ sơ dễ đúng calo mà sai hướng — chọn đúng nguồn đạm mới là phần khó.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Vy, 32 tuổi · 56kg · cao 159cm · theo tín ngưỡng gia đình, KHÔNG ĂN THỊT LỢN.\nGói L1, mục tiêu giảm 3kg. Tập 5 buổi/tuần.\nKhông dị ứng.",
    targetCalories: 1500, targetProtein: 100, tolerancePercent: 10,
    bannedFoods: ["Thịt lợn nạc", "Thịt lợn mỡ", "Thịt mông lợn", "Ba chỉ lợn", "Giò lụa", "Chả lợn", "Mỡ lợn nước", "Gan lợn"],
    explanation: "Kiêng vì tín ngưỡng phải được tôn trọng đúng như kiêng vì dị ứng — không có chuyện \"một chút cũng được\". Bù bằng gà, bò, cá, trứng; và nhớ rằng giò chả cũng là thịt lợn.",
  },
  {
    kind: "SPECIAL",
    clientProfile: "Chị Xoan, 42 tuổi · 68kg · cao 157cm · CƯỜNG GIÁP đang điều trị, bác sĩ dặn không tự ý ăn kiêng.\nMuốn giảm 4kg. Tập 4 buổi/tuần, có giấy đồng ý của bác sĩ.\nKhông dị ứng.",
    targetCalories: 1750, targetProtein: 110, tolerancePercent: 10, bannedFoods: [],
    explanation: "Cường giáp làm mức tiêu hao tăng lên, và bệnh nhân đang điều trị thì không được đặt thâm hụt sâu. Chỉ tiêu ở đây gần mức duy trì — giảm cân chậm là chấp nhận được, còn ăn kiêng tuỳ tiện thì không.",
  },
];
