// Danh mục bài tập của ĐỀ THI — sinh từ Kho bài tập bằng scripts/gen-exercises-data.ts
//
// Vì sao chép ra file tĩnh thay vì đọc thẳng bảng workout_exercises: đề thi phải
// đứng yên. Admin sửa Kho bài tập giữa kỳ mà đề đổi theo thì bài đã chấm không
// tái lập được, và người thi hôm sau gặp một danh mục khác người thi hôm trước.
// Cùng lý do khiến lib/foods-data.ts là file tĩnh.
//
// Chạy lại script khi muốn danh mục đề bắt kịp Kho bài tập.

export type ExamExercise = {
  name: string;
  /** Mẫu vận động — Squat, Hinge, Push, Pull, Core… */
  pattern: string;
  /** Nhóm dùng để chấm khối lượng buổi tập. */
  group: "LOWER" | "UPPER" | "CORE" | "CARDIO" | "OTHER";
};

export const EXAM_EXERCISES: ExamExercise[] = [
  { name: "Bước leo máy (Stair Master)", pattern: "cardio", group: "CARDIO" },
  { name: "Elliptical", pattern: "cardio", group: "CARDIO" },
  { name: "HIIT 20/10", pattern: "cardio", group: "CARDIO" },
  { name: "Nhảy dây", pattern: "cardio", group: "CARDIO" },
  { name: "Treadmill nhịp đều", pattern: "cardio", group: "CARDIO" },
  { name: "Xe đạp tại chỗ", pattern: "cardio", group: "CARDIO" },
  { name: "Box Jump", pattern: "HIT", group: "CARDIO" },
  { name: "Burpees", pattern: "HIT", group: "CARDIO" },
  { name: "Face Pull (Kéo lưng trên với cáp)", pattern: "HIT", group: "CARDIO" },
  { name: "Full Butt Touch (Chạy gót chạm mông)", pattern: "HIT", group: "CARDIO" },
  { name: "Full Half Burpee (Burpee nhanh)", pattern: "HIT", group: "CARDIO" },
  { name: "Full High Knee (Chạy nâng cao gối)", pattern: "HIT", group: "CARDIO" },
  { name: "Full Jumping Jack (Nhảy Jack)", pattern: "HIT", group: "CARDIO" },
  { name: "Full Plank Back & Forth (Plank nhảy trước & sau)", pattern: "HIT", group: "CARDIO" },
  { name: "Full Plank In & Out (Plank bật nhảy)", pattern: "HIT", group: "CARDIO" },
  { name: "Full Plank Shoulder Touch (Plank chạm vai nhanh)", pattern: "HIT", group: "CARDIO" },
  { name: "Half Burpee", pattern: "HIT", group: "CARDIO" },
  { name: "High Mountain Climber (Chạy leo núi)", pattern: "HIT", group: "CARDIO" },
  { name: "Jump Squat nặng", pattern: "HIT", group: "CARDIO" },
  { name: "Mid Butt Touch (Đi bộ nhanh gót chạm mông)", pattern: "HIT", group: "CARDIO" },
  { name: "Mid Half Burpee (Burpee vừa)", pattern: "HIT", group: "CARDIO" },
  { name: "Mid High Knee (Đi bộ nhanh nâng cao gối)", pattern: "HIT", group: "CARDIO" },
  { name: "Mid Jumping Jack (Nhảy Jack vừa)", pattern: "HIT", group: "CARDIO" },
  { name: "Mid Mountain Climber (Đi bộ nhanh leo núi)", pattern: "HIT", group: "CARDIO" },
  { name: "Mid Plank Back & Forth (Plank đi bộ nhanh trước & sau)", pattern: "HIT", group: "CARDIO" },
  { name: "Mid Plank In & Out (Plank nhảy vừa)", pattern: "HIT", group: "CARDIO" },
  { name: "Mid Plank Shoulder Touch (Plank chạm vai vừa)", pattern: "HIT", group: "CARDIO" },
  { name: "Mountain Climbers", pattern: "HIT", group: "CARDIO" },
  { name: "Shoulder Pull (Kéo lưng ngang với cáp)", pattern: "HIT", group: "CARDIO" },
  { name: "Skater Jumps", pattern: "HIT", group: "CARDIO" },
  { name: "Slow Butt Touch (Đi bộ gót chạm mông)", pattern: "HIT", group: "CARDIO" },
  { name: "Slow Half Burpee (Burpee chậm)", pattern: "HIT", group: "CARDIO" },
  { name: "Slow High Knee (Đi bộ nâng cao gối)", pattern: "HIT", group: "CARDIO" },
  { name: "Slow Jumping Jack (Nhảy Jack chậm)", pattern: "HIT", group: "CARDIO" },
  { name: "Slow Mountain Climber (Đi bộ leo núi)", pattern: "HIT", group: "CARDIO" },
  { name: "Slow Plank Back & Forth (Plank đi bộ trước & sau)", pattern: "HIT", group: "CARDIO" },
  { name: "Slow Plank In & Out (Plank nhảy chậm)", pattern: "HIT", group: "CARDIO" },
  { name: "Slow Plank Shoulder Touch (Plank chạm vai chậm)", pattern: "HIT", group: "CARDIO" },
  { name: "Sprint tại chỗ", pattern: "HIT", group: "CARDIO" },
  { name: "Battle Rope (Đập dây thừng)", pattern: "MIT", group: "CARDIO" },
  { name: "Bicycle Crunch (Gập bụng đạp xe)", pattern: "MIT", group: "CARDIO" },
  { name: "Butt Touch (Gót chạm mông)", pattern: "MIT", group: "CARDIO" },
  { name: "Deadlift & Row (Gập hông & Kéo lưng)", pattern: "MIT", group: "CARDIO" },
  { name: "Farmer Walk (Xách tạ đi bộ)", pattern: "MIT", group: "CARDIO" },
  { name: "Flutter Kick (Đá cắt kéo)", pattern: "MIT", group: "CARDIO" },
  { name: "Half Burpee (Bật nhảy)", pattern: "MIT", group: "CARDIO" },
  { name: "High Knee (Nâng cao gối)", pattern: "MIT", group: "CARDIO" },
  { name: "Inch Worm (Sâu đo)", pattern: "MIT", group: "CARDIO" },
  { name: "Jumping Jack (Nhảy Jack)", pattern: "MIT", group: "CARDIO" },
  { name: "Mountain Climber (Leo núi)", pattern: "MIT", group: "CARDIO" },
  { name: "Plank Back & Forth (Plank nhảy trước & sau)", pattern: "MIT", group: "CARDIO" },
  { name: "Plank In & Out (Plank bật nhảy)", pattern: "MIT", group: "CARDIO" },
  { name: "Plank Shoulder Touch (Plank chạm vai)", pattern: "MIT", group: "CARDIO" },
  { name: "Sand Bag Carry (Xách bao cát đi bộ)", pattern: "MIT", group: "CARDIO" },
  { name: "Sand Bag Holy Combo (Bật Squat + Đẩy vai + Bước Lunge)", pattern: "MIT", group: "CARDIO" },
  { name: "Sand Bag Kick Squat (Squat bật với bao cát)", pattern: "MIT", group: "CARDIO" },
  { name: "Sand Bag Push Press (Bật đẩy vai với bao cát)", pattern: "MIT", group: "CARDIO" },
  { name: "Sand Bag Walking Lunge (Bước Lunge với bao cát)", pattern: "MIT", group: "CARDIO" },
  { name: "Squat & Press (Squat & Đẩy vai)", pattern: "MIT", group: "CARDIO" },
  { name: "Ab Rollout", pattern: "core", group: "CORE" },
  { name: "Bicycle Crunch", pattern: "core", group: "CORE" },
  { name: "Cable Crunch", pattern: "core", group: "CORE" },
  { name: "Hanging Leg Raise", pattern: "core", group: "CORE" },
  { name: "Russian Twist", pattern: "core", group: "CORE" },
  { name: "V-Up", pattern: "core", group: "CORE" },
  { name: "Bear Plank (Plank gấu)", pattern: "Core", group: "CORE" },
  { name: "Bird Dog (Chim, chó)", pattern: "Core", group: "CORE" },
  { name: "Dead Bug (Con bọ chết)", pattern: "Core", group: "CORE" },
  { name: "Flutter Kick (Đá bụng cắt kéo)", pattern: "Core", group: "CORE" },
  { name: "Full Plank (Plank thường)", pattern: "Core", group: "CORE" },
  { name: "Full Side Plank (Plank nghiêng)", pattern: "Core", group: "CORE" },
  { name: "Knee Plank (Plank bằng gối)", pattern: "Core", group: "CORE" },
  { name: "Knee Side Plank (Plank nghiêng bằng gối)", pattern: "Core", group: "CORE" },
  { name: "PPT Plank (Plank tôm)", pattern: "Core", group: "CORE" },
  { name: "Straight Plank (Plank thẳng tay)", pattern: "Core", group: "CORE" },
  { name: "Torso Elevated 90 Degree Bend Heel On Ground Leg Raise (Dựng người đá bụng chân gập 90 độ, gót chạm sàn)", pattern: "Core", group: "CORE" },
  { name: "Torso Elevated 90 Degree Bend Leg Raise (Dựng người đá bụng chân gập 90 độ)", pattern: "Core", group: "CORE" },
  { name: "Torso Elevated Straight Leg Raise (Dựng người đá bụng với chân thẳng)", pattern: "Core", group: "CORE" },
  { name: "Leg Press Calf Raise", pattern: "calf", group: "LOWER" },
  { name: "Seated Calf Raise", pattern: "calf", group: "LOWER" },
  { name: "Single Leg Calf Raise", pattern: "calf", group: "LOWER" },
  { name: "Standing Calf Raise", pattern: "calf", group: "LOWER" },
  { name: "Abduction Machine", pattern: "glute", group: "LOWER" },
  { name: "Barbell Hip Thrust", pattern: "glute", group: "LOWER" },
  { name: "Cable Kickback", pattern: "glute", group: "LOWER" },
  { name: "Single Leg Glute Bridge", pattern: "glute", group: "LOWER" },
  { name: "Sumo Deadlift", pattern: "glute", group: "LOWER" },
  { name: "Banded Hip Thrust", pattern: "Glute Attack", group: "LOWER" },
  { name: "Barbell Hip Thrust nặng", pattern: "Glute Attack", group: "LOWER" },
  { name: "Bulgarian Split Squat (mông tập trung)", pattern: "Glute Attack", group: "LOWER" },
  { name: "Cable Kickback nặng", pattern: "Glute Attack", group: "LOWER" },
  { name: "Cable Pull-Through", pattern: "Glute Attack", group: "LOWER" },
  { name: "Cable Pullthrough (Gập hông với dây cáp)", pattern: "Glute Attack", group: "LOWER" },
  { name: "Mini-band Crab Walk (Đi cua với dây)", pattern: "Glute Attack", group: "LOWER" },
  { name: "Mini-band Holy Triad (Quỳ đá 3 góc mông)", pattern: "Glute Attack", group: "LOWER" },
  { name: "Mini-band Lying Dual Kickback (Nằm ghế đá mông với dây)", pattern: "Glute Attack", group: "LOWER" },
  { name: "Mini-band Lying Leg Raise (Nằm nghiêng nâng chân với dây)", pattern: "Glute Attack", group: "LOWER" },
  { name: "Mini-band Quadruped Donkey Kick (Quỳ đá mông với dây)", pattern: "Glute Attack", group: "LOWER" },
  { name: "Mini-band Quadruped Hip Abduction (Quỳ mở hông với dây)", pattern: "Glute Attack", group: "LOWER" },
  { name: "Single Leg Hip Thrust tạ đòn", pattern: "Glute Attack", group: "LOWER" },
  { name: "Lying Leg Curl", pattern: "hamstring", group: "LOWER" },
  { name: "Seated Leg Curl", pattern: "hamstring", group: "LOWER" },
  { name: "Barbell Glute Bridge (Cây cầu với thanh đòn)", pattern: "Hinge", group: "LOWER" },
  { name: "Barbell Hip Thrust (Đẩy hông với thanh đòn)", pattern: "Hinge", group: "LOWER" },
  { name: "Barbell Romanian Deadlift (Gập hông với thanh đòn)", pattern: "Hinge", group: "LOWER" },
  { name: "DB B-Stance Romanian Deadlift (Gập hông lệch chân với tạ đơn)", pattern: "Hinge", group: "LOWER" },
  { name: "Deadlift kiểu Sumo", pattern: "Hinge", group: "LOWER" },
  { name: "Dumbbell Glute Bridge (Cây cầu với tạ đơn)", pattern: "Hinge", group: "LOWER" },
  { name: "Dumbbell Hip Thrust (Đẩy hông với tạ đơn)", pattern: "Hinge", group: "LOWER" },
  { name: "Dumbbell Romanian Deadlift (Gập hông với tạ đơn)", pattern: "Hinge", group: "LOWER" },
  { name: "Glute Bridge (Cây cầu)", pattern: "Hinge", group: "LOWER" },
  { name: "Good Morning nặng", pattern: "Hinge", group: "LOWER" },
  { name: "Kneeling Hip Hinge (Quỳ gối gập hông)", pattern: "Hinge", group: "LOWER" },
  { name: "Nordic Curl", pattern: "Hinge", group: "LOWER" },
  { name: "Romanian Deadlift (tạ đòn)", pattern: "Hinge", group: "LOWER" },
  { name: "Single Leg BB Glute Bridge (Đẩy hông 1 chân với thanh đòn)", pattern: "Hinge", group: "LOWER" },
  { name: "Single Leg BB Hip Thrust (Đẩy hông 1 chân với thanh đòn)", pattern: "Hinge", group: "LOWER" },
  { name: "Single Leg DB Glute Bridge (Cây cầu 1 chân với tạ đơn)", pattern: "Hinge", group: "LOWER" },
  { name: "Single Leg DB Hip Thrust (Đẩy hông 1 chân với tạ đơn)", pattern: "Hinge", group: "LOWER" },
  { name: "Single Leg Romanian Deadlift", pattern: "Hinge", group: "LOWER" },
  { name: "Standing Hip Hinge (Đứng gập hông)", pattern: "Hinge", group: "LOWER" },
  { name: "Stiff Leg Deadlift nặng", pattern: "Hinge", group: "LOWER" },
  { name: "Adduction Machine", pattern: "inner_thigh", group: "LOWER" },
  { name: "Cable Adduction", pattern: "inner_thigh", group: "LOWER" },
  { name: "Pilates Scissor", pattern: "inner_thigh", group: "LOWER" },
  { name: "Side Lying Leg Raise (đùi trong)", pattern: "inner_thigh", group: "LOWER" },
  { name: "Sumo Squat rộng", pattern: "inner_thigh", group: "LOWER" },
  { name: "Abduction Machine nặng", pattern: "Lower Isolate", group: "LOWER" },
  { name: "Cable Hip Abduction (Mở hông với dây cáp)", pattern: "Lower Isolate", group: "LOWER" },
  { name: "Cable Kick Back (Đá hông với dây cáp)", pattern: "Lower Isolate", group: "LOWER" },
  { name: "Hip Extension (Gập hông trên ghế)", pattern: "Lower Isolate", group: "LOWER" },
  { name: "Hip Extension (Gập hông với ghế)", pattern: "Lower Isolate", group: "LOWER" },
  { name: "Leg Curl nặng", pattern: "Lower Isolate", group: "LOWER" },
  { name: "Leg Extension (Đá đùi trước)", pattern: "Lower Isolate", group: "LOWER" },
  { name: "Leg Extension nặng", pattern: "Lower Isolate", group: "LOWER" },
  { name: "Nordic Curl hỗ trợ", pattern: "Lower Isolate", group: "LOWER" },
  { name: "Seated Leg Curl (Cuộn đùi sau)", pattern: "Lower Isolate", group: "LOWER" },
  { name: "Single Leg Leg Press", pattern: "Lower Isolate", group: "LOWER" },
  { name: "Bodyweight Box Jump (Nhảy lên bục không tạ)", pattern: "Plyo Lower", group: "LOWER" },
  { name: "Bodyweight Crab Walk to Jump (Đi cua rồi nhảy không tạ)", pattern: "Plyo Lower", group: "LOWER" },
  { name: "Bodyweight Jump Heel Tap Squat (Squat không tạ, nhảy gót chạm nhau)", pattern: "Plyo Lower", group: "LOWER" },
  { name: "Bodyweight Jump Pop Squat (Squat không tạ, nhảy vào ra)", pattern: "Plyo Lower", group: "LOWER" },
  { name: "Bodyweight Jump Squat In Place (Squat không tạ, nhảy tại chỗ)", pattern: "Plyo Lower", group: "LOWER" },
  { name: "Bodyweight Jumping Lunge (Nhảy đổi chân trước, chân sau không tạ)", pattern: "Plyo Lower", group: "LOWER" },
  { name: "Bodyweight Skater Hop (Nhảy lắt léo 2 bên không tạ)", pattern: "Plyo Lower", group: "LOWER" },
  { name: "Bodyweight Split Squat Jump (Nhảy chân trước, chân sau không tạ)", pattern: "Plyo Lower", group: "LOWER" },
  { name: "Hack Squat", pattern: "quad", group: "LOWER" },
  { name: "Leg Extension", pattern: "quad", group: "LOWER" },
  { name: "Leg Press", pattern: "quad", group: "LOWER" },
  { name: "Lunges đi bộ", pattern: "quad", group: "LOWER" },
  { name: "Air Box Squat (Squat người không với bục)", pattern: "Squat", group: "LOWER" },
  { name: "Air Box Squat (Squat với bục)", pattern: "Squat", group: "LOWER" },
  { name: "Air Split Squat (Squat chân trước, chân sau)", pattern: "Squat", group: "LOWER" },
  { name: "Air Squat (Squat người không)", pattern: "Squat", group: "LOWER" },
  { name: "Assisted High Step Up (Bước bục cao có trợ lực)", pattern: "Squat", group: "LOWER" },
  { name: "Assisted Low Step Up (Bước bục thấp có trợ lực)", pattern: "Squat", group: "LOWER" },
  { name: "Assisted Mid Step Up (Bước bục vừa có trợ lực)", pattern: "Squat", group: "LOWER" },
  { name: "Assisted Split Squat (Squat chân trước, chân sau trợ lực)", pattern: "Squat", group: "LOWER" },
  { name: "Barbell Back Squat", pattern: "Squat", group: "LOWER" },
  { name: "Barbell High Bar Back Squat (Squat thanh đòn)", pattern: "Squat", group: "LOWER" },
  { name: "Barbell Split Squat (Squat chân trước, chân sau với thanh đòn)", pattern: "Squat", group: "LOWER" },
  { name: "Bulgarian Split Squat", pattern: "Squat", group: "LOWER" },
  { name: "DB Assisted High Step Up (Bước bục cao trợ lực với tạ đơn)", pattern: "Squat", group: "LOWER" },
  { name: "DB Assisted Low Step Up (Bước bục thấp trợ lực với tạ đơn)", pattern: "Squat", group: "LOWER" },
  { name: "DB Assisted Mid Step Up (Bước bục vừa trợ lực với tạ đơn)", pattern: "Squat", group: "LOWER" },
  { name: "DB Assisted Split Squat (Squat chân trước, chân sau trợ lực với tạ đơn)", pattern: "Squat", group: "LOWER" },
  { name: "DB High Step up (Bước bục cao với tạ đơn)", pattern: "Squat", group: "LOWER" },
  { name: "DB Low Step up (Bước bục thấp với tạ đơn)", pattern: "Squat", group: "LOWER" },
  { name: "DB Mid Step up (Bước bục vừa với tạ đơn)", pattern: "Squat", group: "LOWER" },
  { name: "Dual Dumbbell Goblet Squat (Squat với 2 tạ đơn)", pattern: "Squat", group: "LOWER" },
  { name: "Dumbbell Goblet Box Squat (Squat tạ đơn với bục)", pattern: "Squat", group: "LOWER" },
  { name: "Dumbbell Goblet Squat (Squat với tạ đơn)", pattern: "Squat", group: "LOWER" },
  { name: "Dumbbell Split Squat (Squat chân trước chân sau với tạ đơn)", pattern: "Squat", group: "LOWER" },
  { name: "Front Squat", pattern: "Squat", group: "LOWER" },
  { name: "Goblet Squat nặng", pattern: "Squat", group: "LOWER" },
  { name: "Heel Air Squat (Squat người không, kê gót)", pattern: "Squat", group: "LOWER" },
  { name: "Heel Dual Dumbbell Goblet Squat (Squat 2 tạ đơn, kê gót)", pattern: "Squat", group: "LOWER" },
  { name: "Heel Dumbbell Goblet Squat (Squat tạ đơn, kê gót)", pattern: "Squat", group: "LOWER" },
  { name: "High Step Up (Bước bục cao)", pattern: "Squat", group: "LOWER" },
  { name: "Leg Press đơn chân", pattern: "Squat", group: "LOWER" },
  { name: "Low Step Up (Bước bục thấp)", pattern: "Squat", group: "LOWER" },
  { name: "Mid Step Up (Bước bục vừa)", pattern: "Squat", group: "LOWER" },
  { name: "Pistol Squat hỗ trợ", pattern: "Squat", group: "LOWER" },
  { name: "Wall Sit (Squat dựa tường)", pattern: "Squat", group: "LOWER" },
  { name: "Foam roll toàn thân", pattern: "cooldown", group: "OTHER" },
  { name: "Giãn cơ tĩnh toàn thân", pattern: "cooldown", group: "OTHER" },
  { name: "Thở dưỡng sinh", pattern: "cooldown", group: "OTHER" },
  { name: "Yoga hạ nhiệt", pattern: "cooldown", group: "OTHER" },
  { name: "Đạp xe tại chỗ (thấp)", pattern: "warmup", group: "OTHER" },
  { name: "Đi bộ máy treadmill", pattern: "warmup", group: "OTHER" },
  { name: "Dynamic stretching", pattern: "warmup", group: "OTHER" },
  { name: "Nhảy dây nhẹ", pattern: "warmup", group: "OTHER" },
  { name: "Xoay khớp toàn thân", pattern: "warmup", group: "OTHER" },
  { name: "Cable Bicep Curl", pattern: "arm", group: "UPPER" },
  { name: "Dumbbell Bicep Curl", pattern: "arm", group: "UPPER" },
  { name: "Hammer Curl", pattern: "arm", group: "UPPER" },
  { name: "Overhead Tricep Extension", pattern: "arm", group: "UPPER" },
  { name: "Skull Crusher", pattern: "arm", group: "UPPER" },
  { name: "Tricep Pushdown (dây)", pattern: "arm", group: "UPPER" },
  { name: "Cable Pullover", pattern: "back", group: "UPPER" },
  { name: "Pull-Up", pattern: "back", group: "UPPER" },
  { name: "T-Bar Row", pattern: "back", group: "UPPER" },
  { name: "Dumbbell Deadlift & Row (Gập hông & kéo lưng)", pattern: "Plyo Upper", group: "UPPER" },
  { name: "Dumbbell Squat & Press (Squat & đẩy vai)", pattern: "Plyo Upper", group: "UPPER" },
  { name: "Full Plyo Push Up (Chống đẩy bật người)", pattern: "Plyo Upper", group: "UPPER" },
  { name: "Hand Clap Push Up (Chống đẩy vỗ tay)", pattern: "Plyo Upper", group: "UPPER" },
  { name: "Incline Plyo Push Up (Chống đẩy dốc trên bật người)", pattern: "Plyo Upper", group: "UPPER" },
  { name: "Kettlebell/Dumbbell Swing (Lăng tạ ấm hoặc tạ đơn)", pattern: "Plyo Upper", group: "UPPER" },
  { name: "Assisted 1 Arm DB Row (Kéo lưng ngang 1 tay có trợ lực)", pattern: "Pull", group: "UPPER" },
  { name: "Barbell Bent-Over Row", pattern: "Pull", group: "UPPER" },
  { name: "Bayesian Cable Pullover (Vớt tạ gập người bằng dây cáp)", pattern: "Pull", group: "UPPER" },
  { name: "BB Bent Row (Gập người kéo lưng ngang với thanh đòn)", pattern: "Pull", group: "UPPER" },
  { name: "Cable Pullover (Vớt tạ bằng dây cáp)", pattern: "Pull", group: "UPPER" },
  { name: "Cable Pullover nặng", pattern: "Pull", group: "UPPER" },
  { name: "Chest Supported Row", pattern: "Pull", group: "UPPER" },
  { name: "DB Bent Row (Gập người kéo lưng ngang với tạ đơn)", pattern: "Pull", group: "UPPER" },
  { name: "Dumbbell Prone Row (Nằm kéo lưng ngang với ghế)", pattern: "Pull", group: "UPPER" },
  { name: "Meadows Row", pattern: "Pull", group: "UPPER" },
  { name: "OVH Lat Pulldown (Kéo lưng dọc úp tay)", pattern: "Pull", group: "UPPER" },
  { name: "Rack Pull", pattern: "Pull", group: "UPPER" },
  { name: "Seated Cable Row (Ngồi kéo lưng ngang với cáp)", pattern: "Pull", group: "UPPER" },
  { name: "Standing Cable Row (Đứng kéo lưng ngang với cáp)", pattern: "Pull", group: "UPPER" },
  { name: "UDH Lat Pulldown (Kéo lưng dọc ngửa tay)", pattern: "Pull", group: "UPPER" },
  { name: "Weighted Pull-Up", pattern: "Pull", group: "UPPER" },
  { name: "Arnold Press", pattern: "Push", group: "UPPER" },
  { name: "Barbell Bench Press", pattern: "Push", group: "UPPER" },
  { name: "Close-Grip Bench Press", pattern: "Push", group: "UPPER" },
  { name: "Dumbbell Bench Press (Đẩy ngực ghế thẳng)", pattern: "Push", group: "UPPER" },
  { name: "Dumbbell Floor Press (Đẩy ngực nằm sàn)", pattern: "Push", group: "UPPER" },
  { name: "Dumbbell Shoulder Press nặng", pattern: "Push", group: "UPPER" },
  { name: "Full Push-ups (Chống đẩy full)", pattern: "Push", group: "UPPER" },
  { name: "Incline Barbell Press", pattern: "Push", group: "UPPER" },
  { name: "Incline Dumbbell Press (Đẩy ngực ghế dốc)", pattern: "Push", group: "UPPER" },
  { name: "Incline Push-ups (Chống đẩy với thanh đòn)", pattern: "Push", group: "UPPER" },
  { name: "Knee Push-ups (Chống đẩy với gối)", pattern: "Push", group: "UPPER" },
  { name: "Overhead Press", pattern: "Push", group: "UPPER" },
  { name: "Seated DB Shoulder Press (Ngồi đẩy vai)", pattern: "Push", group: "UPPER" },
  { name: "Standing DB Shoulder Press (Đứng đẩy vai)", pattern: "Push", group: "UPPER" },
  { name: "Cable Lateral Raise", pattern: "shoulder", group: "UPPER" },
  { name: "Dumbbell Lateral Raise", pattern: "shoulder", group: "UPPER" },
  { name: "Dumbbell Shoulder Press", pattern: "shoulder", group: "UPPER" },
  { name: "Front Raise", pattern: "shoulder", group: "UPPER" },
  { name: "Upright Row", pattern: "shoulder", group: "UPPER" },
  { name: "Bear Plank (Plank Gấu)", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Cable Chest Fly (Bay ngực với cáp)", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Cable Triceps Extension (Tập tay sau với cáp)", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Crunches (Gập bụng)", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Dumbbell Bicep Curl nặng", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Dumbbell Front Raise (Bay vai trước với tạ đơn)", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Dumbbell Front Raise (Bay vai trước)", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Dumbbell Lateral Raise nặng", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Face Pull", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Lying Leg Raise (Đá bụng dưới)", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Reverse Plank (Plank ngược)", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Side Plank (Plank nghiêng)", pattern: "Upper Isolate", group: "UPPER" },
  { name: "Straight Plank (Plank thường)", pattern: "Upper Isolate", group: "UPPER" },
];

/** Tra nhanh theo tên. */
export const EXERCISE_BY_NAME = new Map(EXAM_EXERCISES.map((e) => [e.name, e]));
